#' Modify ME-2 ini file using R
#' 
#' The .ini file, which is needed to  provide information to ME-2, can be 
#' programmatically changed using this function. Not all information can be
#' changed yet.
#'
#' @param file name of the ME-2 ini file, can include path. This is also the
#'   file where the output is written to.
#' @param openfile name of the data file for ME-2
#' @param robust use robust calculations
#' @param n2 number of variables
#' @param ns number of samples
#' @param np number of factors
#' @param numtasks number of tasks
#' @param fileid part of the file name of the output files generated by ME-2
#' @param aasmooc1 value for c1 smoothing
#' @param aasmooc3 value for c3 smoothing
#' @param c2 value for c2
#' @param c3 value for c3
#' @param em the error model used in ME-2
#'
#' @examples
#' In this example a "template.ini" is used. This is basically an ini file that
#' contains most of the parameters for the run we want to do. We can use the
#' \code{me2_modify.ini} function to modify the ini, save it as a new file and 
#' use that as input for ME-2.
#'
#' \dontrun{
#' factors <- c(5,6,7,8)
#'
#' for (factor in factors) {
#'    me2_modify_ini(file = "template.ini",
#'                   robust = 1,
#'                   np = factor,
#'                   n2 = 16 #species,
#'                   ns = 1024 #samples,
#'                   aasmooc1 = 2.5,
#'                   aasmooc3 = 0.15,
#'                   c3 = 0.15,
#'                   numtasks = 250,
#'                   openfile = "my_input_data.txt",
#'                   fileid = paste0("my_output_file_", factor))
#'    # run model
#'    shell("me2 template.ini")
#'    # manually rename LOG so it fits with the rest of the files
#'    file.rename("ME2.LOG", paste0("my_output_file_", factor, ".LOG"))
#' }
#' }
#'
#' @return overwriting the provided \code{ini} file with the updated version.
#'
#' @export
#'
#' @import cli
#' @import readr
#' 
me2_modify_ini <- function(file,
                           openfile = NA,
                           robust = NA,
                           n2=NA,
                           ns=NA,
                           np=NA,
                           numtasks = NA,
                           fileid = NA,
                           aasmooc1 = NA,
                           aasmooc3 = NA,
                           c2 = NA,
                           c3 = NA,
                           em = NA){
  
  # check if file exists
  if (!file.exists(file)) {
    cli::cli_abort(c(
      "{.var file} must be a valid file:",
      "x" = "File '{file}' does not exists."
    ))
  }
  
  
  # read file
  ini_file <- readr::read_file(file)
  
  
  if(!is.na(robust)) {
    # replace number of variables
    ini_file <- gsub("robust=[0-1];", paste0("robust=",robust,";") , ini_file)
  }
  
  if(!is.na(n2)) {
    # replace number of variables
    ini_file <- gsub("n2=[0-9]+;", paste0("n2=",n2,";") , ini_file)
  }
  
  if(!is.na(ns)) {
    # replace total number of samples
    ini_file <- gsub("ns=[0-9]+;", paste0("ns=",ns,";") , ini_file)
  }
  
  if(!is.na(np)) {
    # replace number of factors
    ini_file <- gsub("np=[0-9]+;", paste0("np=",np,";") , ini_file)
  }
  
  if(!is.na(fileid)) {
    # replace main part of title of files to be written
    ini_file <- gsub("FILEID\\[1\\]=\\'.*\\';\\s+% Main part of title of files to be written", paste0("FILEID[1]='", fileid, "';      % Main part of title of files to be written") , ini_file)
  }
  
  if(!is.na(openfile)) {
    # replace openfile with data
    ini_file <- gsub("openfile\\s+30,\\s+\\'.*\\',\\s+R,\\s+'old',\\s+6000;", paste0("openfile  30,     '", openfile, "',         R,    'old',          6000;") , ini_file)
  }
  
  if(!is.na(aasmooc1)) {
    # replace aasmooc1 with data
    ini_file <- gsub("\'aasmooc1\'=[+-]?(?:\\d*\\.)?\\d+,", paste0("'aasmooc1'=", aasmooc1,",") , ini_file)
  }
  
  if(!is.na(aasmooc3)) {
    # replace aasmooc3 with data
    ini_file <- gsub("\'aasmooc3\'=[+-]?(?:\\d*\\.)?\\d+,", paste0("'aasmooc3'=", aasmooc3,",") , ini_file)
  }
  
  if(!is.na(c2)) {
    # c2 coefficent
    ini_file <- gsub("c2=[+-]?(?:\\d*\\.)?\\d+;", paste0("c2=",c2,";") , ini_file)
  }
  
  if(!is.na(c3)) {
    # c3 coefficent
    ini_file <- gsub("c3=[+-]?(?:\\d*\\.)?\\d+;", paste0("c3=",c3,";") , ini_file)
  }
  
  if(!is.na(em)) {
    # error model
    ini_file <- gsub("em=[+-]?(?:\\d*\\.)?\\d+;", paste0("em=",em,";") , ini_file)
  }
  
  if(!is.na(numtasks)) {
    ini_file <- gsub("numtasks=[+-]?(?:\\d*\\.)?\\d+;", paste0("numtasks=",numtasks,";") , ini_file)
  }
  
  
  # write ini_file
  readr::write_file(ini_file, file)
  
}
